name: "test-local"
on:
  push:
    branches:
      - master
      - feature/add

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run custom action
        uses: ./
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY_STAGING }}
          parsley-componentname: cicd
          parsley-environment: "staging"
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY_STAGING }}
      - name: Run custom action (Production)
        if: startsWith(github.ref, 'refs/tags/')
        uses: ./
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY_PRODUCTION }}
          parsley-componentname: cicd
          parsley-environment: "production"
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY_PRODUCTION }}

